-- Create students table
CREATE TABLE IF NOT EXISTS students (
  user_id TEXT PRIMARY KEY,
  fullname TEXT,
  muid TEXT,
  karma INTEGER,
  rank INTEGER,
  level TEXT,
  joint_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create karma_history table
CREATE TABLE IF NOT EXISTS karma_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT REFERENCES students(user_id),
  karma INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create campus_details table
CREATE TABLE IF NOT EXISTS campus_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank INTEGER,
  karma INTEGER,
  total_members INTEGER,
  active_members INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
